# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ('entrada',), 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
